name: build-and-release

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@c841a80c0550ba75f1d6f29e655d3e6bf9fced13 # main
    needs: build
    if: "${{ success() && always() && ! startsWith(github.event.head_commit.message, 'chore(release): ') }}"
    permissions:
      contents: write # for creating release

  upload-release-artifact:
    runs-on: ubuntu-24.04
    needs: release
    if: ${{ success() && always() && needs.release.outputs.tag }}
    permissions:
      contents: write # for uploading release artifact

    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: build-result
          path: ./result

      - name: Upload Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: result/lib/CustomModels.dll
          tag_name: ${{ needs.release.outputs.tag }}
